Train:
  YoutubeVOS:
    image_dir: /data00/multidoor_dataset/youtube_vos_2019/train/JPEGImages/
    anno: /data00/multidoor_dataset/youtube_vos_2019/train/Annotations/
    meta: /data00/multidoor_dataset/youtube_vos_2019/train/meta.json
    caption: /data/home/sqy/PythonProjects/multimodal/LLaVA/caption_ytvos19.json

  YoutubeVIS:
    image_dir: /data00/datasets/youtube_vis_2019/train/JPEGImages/
    anno: /data00/datasets/youtube_vis_2019/train/Annotations/
    meta: /data00/datasets/youtube_vis_2019/train/meta.json
    caption: /data/home/sqy/PythonProjects/multimodal/LLaVA/caption_ytvis19.json

  YoutubeVIS21:
    root: /data00/multidoor_dataset/youtube_vis_2021/train/JPEGImages/
    anno: /data00/multidoor_dataset/youtube_vis_2021/train/instances.json
    caption: /data/home/sqy/PythonProjects/multimodal/LLaVA/caption_ytvis21.json

  VIPSeg:
    image_dir: /data00/multidoor_dataset/VIPSeg/VIPSeg_720P/images/
    anno: /data00/multidoor_dataset/VIPSeg/VIPSeg_720P/panomasksRGB/
    meta: /data00/multidoor_dataset/VIPSeg/VIPSeg_720P/panoptic_gt_VIPSeg.json
    caption: /data/home/sqy/PythonProjects/multimodal/LLaVA/caption_vipseg.json

  UVO:
    train:
      image_dir: /data00/multidoor_dataset/UVO/uvo_frames_sparse
      video_json: /data00/multidoor_dataset/UVO/VideoSparseSet/UVO_sparse_train_video_with_interpolation.json
      image_json: /data00/multidoor_dataset/UVO/VideoSparseSet/UVO_sparse_train_video_with_interpolation_reorg.json
    val:
      image_dir: path/UVO/uvo_frames_sparse
      video_json: path/UVO/VideoSparseSet/UVO_sparse_val_video_with_interpolation.json
      image_json: path/UVO/VideoSparseSet/UVO_sparse_val_video_interpolation_reorg.json

  Mose:
    image_dir: /data00/multidoor_dataset/MOSE/train/JPEGImages/
    anno: /data00/multidoor_dataset/MOSE/train/Annotations/
    caption: ./data/caption_mose.json

  MVImageNet:
    txt: /data00/multidoor_dataset/MVImgNet/mvimagenet.txt
    image_dir: /data00/multidoor_dataset/MVImgNet/
    caption: ./data/caption_mvimagenet.json

  VitonHD:
    image_dir: /data00/multidoor_dataset/VitonHD/train/cloth/

  Dresscode:
    image_dir: /mnt/workspace/xizhi/data/dresscode/DressCode/upper_body/label_maps/

  FashionTryon:
    image_dir: /data00/multidoor_dataset/FashionTryOn/train

  Lvis:
    image_dir: /data00/datasets/coco/train2017
    json_path: /data00/multidoor_dataset/LVIS/lvis_v1_train.json
    caption: ./data/caption_coco.json

  SAM:
    sub1: /data00/multidoor_dataset/sam/0000
    sub2: /data00/multidoor_dataset/sam/0001
    sub3: /data00/multidoor_dataset/sam/0002
    sub4: /data00/multidoor_dataset/sam/0004
    caption: /data/home/sqy/PythonProjects/multimodal/LLaVA/caption_sam.json

  Saliency:
    MSRA_root: path/Saliency/MSRA10K_Imgs_GT/
    TR_root: /data00/multidoor_dataset/DUT/DUTS-TR-Image/
    TE_root: /data00/multidoor_dataset/DUT/DUTS-TE-Image/
    HFlickr_root: /data00/multidoor_dataset/HFlickr/masks/
  
  COCO:
    root: /data00/datasets/coco/train2017/
    annotation: /data00/datasets/coco/annotations/instances_train2017.json
    caption: /data/home/sqy/PythonProjects/multimodal/LLaVA/caption_coco.json

  COCOVal:
    root: /data00/datasets/coco/val2017
    annotation: /data00/datasets/coco/annotations/instances_val2017.json

  HICO:
    Train:
      root: /data00/multidoor_dataset/hico  # path to the hicodet dir
      image_dir: images/train2015   # don't change
      mask_dir: relationships   # dont't change
      annotation: instances_train2015.json  # don't change
    Test:
      root: /data00/multidoor_dataset/hico  # path to the hicodet dir
      image_dir: images/test2015   # don't change
      mask_dir: relationships_test   # dont't change
      annotation: instances_test2015.json  # don't change
  
  PSG:
    root: /data00/datasets/coco # path to coco dir
    relation: /data00/multidoor_dataset/psg/psg.json  # path to json file

  PVSG:
    data_root: /data00/multidoor_dataset/OpenPVSG/data  # path to {data/OpenPVSG/data} dir


Test:
  DreamBooth:
    fg_dir: path/DreamBooth/AnyDoor_DreamBooth
    bg_dir: path/DreamBooth/v1_800

  VitonHDTest:
    image_dir: /data00/multidoor_dataset/VitonHD/test/cloth



